### ISSUE TITLE
Community Exchange Introduction/Tracking

### ISSUE THREAD

**Issue by radville** [Sanju-github002/Chrome-Extension#1]
👋  Hi @Sanju-github002,

I am your GitHub mentor for the GitHub Education, [Community Exchange](https://airtable.com/shrRJ3AvEZQohOdGV) (CX) project. I'll be collaborating with you on preparing your repo for CX. 

You mentioned in your submission that you wanted to submit a `Collaborate` repo. This means that you want to invite other students to collaborate and add features to this repo. I will generate issues, which will provide guidance on how to prepare your repo for a `Collaborate` CX submission on June 1, 2022.

This issue will serve as a tracking issue to track all issues related to CX. I recommend creating a new branch for every issue and opening a pull request to track changes so we can effectively collaborate with each other and merge changes when you and I feel like those changes are ready to be merged on your primary branch. 

If you have any questions or concerns, please feel free to leave a comment on this issue or any of the other issues that are generated. 

I look forward to working with you! :octocat: 

**CX Issues:**

- [x] https://github.com/Sanju-github002/Chrome-Extension/issues/2
- [x] https://github.com/Sanju-github002/Chrome-Extension/issues/3
- [x] https://github.com/Sanju-github002/Chrome-Extension/issues/4
- [x] https://github.com/Sanju-github002/Chrome-Extension/issues/5
- [x] https://github.com/Sanju-github002/Chrome-Extension/issues/6
- [x] https://github.com/Sanju-github002/Chrome-Extension/issues/7

**Comment by sanju-0** [comment]
Hello @radville Ma'am,
Thank you for letting me know these things. I will start working on it as soon as possible I am having my exams currently therefore I will respond late. I will add these things soon. Also, ma'am, I am a beginner in the open-source community, It takes time to make things perfect. First I have to learn then I work on this. I hope you understand it ☺️

**Comment by radville** [comment]
Thanks for completing all the issues I opened! I'll let you know when you can submit this to Community Exchange soon.

**Comment by sanju-0** [comment]
Okay Ma'am and Thank you so much for helping me out whenever I get stuck ☺️✨

**Comment by sanju-0** [comment]
Ma'am can you tell me when i have to submit this project to Community Exchange ??

**Comment by radville** [comment]
I see you submitted it, so closing this issue! Thanks for all the great work!
